name: Update Base Table from Price History

on:
  schedule:
    - cron: '*/15 13-21 * * 1-5'  # Every 15 minutes from 13:00 to 21:59 UTC (9:00–17:59 EST) Mon–Fri
  workflow_dispatch:              # Allows manual trigger

jobs:
  update-base-table:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Update Script
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
        run: |
          python update_base_table_from_price_history.py
